import slugHuntOdds from "./slugHuntOdds.json";

// The eight charted worlds of the Slugterra system, ordered inner -> outer:
// the index is also the orbit position on the Galaxy Map, so it tracks
// distance from the sun -- scorching Cindraxis hugs the star, temperate
// Aurelon sits mid-system, sunless Noctavel is the far edge.
//
// ORDER MATTERS. The index into this array is the value stored in
// campaign_settings.slug_hunt_area (0-7) -- the party's current planet, set
// from the Galaxy Map or the dashboard Slug Hunt panel. It must line up with
// slugHuntOdds.json's `areas` array (generated by scripts/gen_odds.py from
// the slug CSV); the assert below fails loudly in dev if the two ever drift.
//
// Visual/orbital fields drive the Galaxy Map (GalaxyMap.jsx), an SVG on a
// 1000x680 viewBox with the sun at (500, 340):
//   orbitRx / orbitRy  half-axes of the elliptical orbit ring
//   sizeR              planet disc radius
//   periodSec          seconds for one full orbit -- roughly proportional to
//                      the orbit's size (longer path = longer lap). The
//                      innermost world takes ~1 minute; the outermost ~5.
//   phaseDeg           starting angle, so they don't all line up
//   color             disc fill
export const PLANETS = [
  {
    name: "Cindraxis",
    color: "#d5623c",
    orbitRx: 95,
    orbitRy: 60,
    sizeR: 15,
    periodSec: 60,
    phaseDeg: 95,
    blurb:
      "A volcanic world, and it looks the part. Rivers of slow lava carve the landscape into black glass ridges and glowing red seams, the sky hangs a dim heat-shimmer orange, and ash drifts down like snow that never settles. The heat isn't a spike, it's a constant weight, thick enough to taste. Everything solid creaks faintly, as if the rock is being slowly cooked. It's beautiful the way a wound can be beautiful — vivid, raw, and plainly not built for anyone to linger in.",
  },
  {
    name: "Vapenar",
    color: "#c9a98f",
    orbitRx: 150,
    orbitRy: 95,
    sizeR: 15,
    periodSec: 95,
    phaseDeg: 170,
    blurb:
      "A flat, cracked world under constant pressure from below. Geysers erupt across Vapenar without warning, sheets of scalding vapour roll low over the ground, and the air stays thick enough to fog a visor and swallow sound whole — you rarely see more than a few dozen metres. The crust is stained white and orange with mineral salt, brittle in some places, treacherously hollow in others. Nothing here attacks you; it just makes it very hard to know where you're standing until the ground reminds you.",
  },
  {
    name: "Sylvoss",
    color: "#6fae55",
    orbitRx: 206,
    orbitRy: 130,
    sizeR: 18,
    periodSec: 130,
    phaseDeg: 60,
    blurb:
      "A hot, wet jungle world under a permanent green-gold canopy so dense that open sky is a rumour. Rain is always falling somewhere on Sylvoss. Warm pools steam in the clearings, ringed by broad-leafed plants that lean, slowly, toward any moving source of heat. Light comes filtered and dappled rather than direct, and sound carries strangely far — a call from one edge of a clearing reaches the other with unnerving clarity. Something is always moving just out of sight, close enough to hear, never close enough to see.",
  },
  {
    name: "Aurelon",
    color: "#d9c47a",
    orbitRx: 262,
    orbitRy: 165,
    sizeR: 12,
    periodSec: 165,
    phaseDeg: 20,
    blurb:
      "A temperate world that never fully brightens. Its dim orange sun sits low and huge on the horizon through most of the long day, so the whole planet lives in a permanent, gentle late-afternoon light. Wind moves in slow waves across plains of pale, sun-starved grass that hushes rather than rustles, and shallow meltwater streams braid toward a scatter of still ponds and one long, mirror-flat lake. Roots and stunted trees cluster wherever groundwater breaks the surface. There are no cities left — just the low mounds of one that used to be, and the quiet of a place that has been left alone for a very long time.",
  },
  {
    name: "Tesalune",
    color: "#3f8fc4",
    orbitRx: 320,
    orbitRy: 202,
    sizeR: 14,
    periodSec: 205,
    phaseDeg: 255,
    blurb:
      "An ocean planet with no land to speak of — open water to every horizon, broken only by wind-worn rock spires that barely clear the swell, some large enough to stand on. Near the surface the water is startlingly clear; a few dozen metres down it goes black, lit only by drifting shoals of luminous plankton and the slow, cold pulses of things moving far beneath. The waves come slower and heavier than the ones you know, as if the sea itself is older and in less of a hurry. The air tastes of salt and cold stone.",
  },
  {
    name: "Vharsk",
    color: "#7f8a99",
    orbitRx: 378,
    orbitRy: 238,
    sizeR: 16,
    periodSec: 240,
    phaseDeg: 140,
    blurb:
      "A world that split and never healed — a maze of vertical rift canyons kilometres deep, their walls raw and unweathered, water-slicked in places, bone-dry and crumbling in others. Updrafts howl through the narrower shafts hard enough to lift a person off their feet, and a dropped stone can fall for a full minute before the sound of it landing comes back, if it ever does. Sunlight reaches only the upper canyon; below that there's nothing, and then, gradually, something else — a cold blue-green glow bleeding up from fissures no survey has ever mapped.",
  },
  {
    name: "Keldrath",
    color: "#9db4c0",
    orbitRx: 432,
    orbitRy: 268,
    sizeR: 14,
    periodSec: 275,
    phaseDeg: 300,
    blurb:
      "A cold, high, wind-scoured world of grey mountains and knife-edge ridgelines, riven with fissures that breathe faint volcanic heat into the thin air. Hot springs pool in the folds between ridges, steaming even in the freezing passes above them, and the wind moves through the peaks in a low, constant moan the rock shapes into something almost like a voice. Visibility is enormous; the footing is murderous — loose scree, narrow ledges, sudden drops. At night the mineral-laden springs glow faintly, the only warm light in the whole landscape.",
  },
  {
    name: "Noctavel",
    color: "#6b5bd0",
    orbitRx: 470,
    orbitRy: 292,
    sizeR: 12,
    periodSec: 300,
    phaseDeg: 210,
    blurb:
      "The strangest world in the system, and the quietest. Noctavel has no sun that anyone has found; its surface sits in a cool mineral stillness under a black sky, lit only by veins of slow bioluminescence running through the rock like exposed nerves, pulsing on a rhythm that matches nothing human. The plains open into spaces too vast for any lamp to cross. The air itself feels attended to — not hostile, not empty, just deeply, patiently aware. Nothing here moves quickly, because nothing here has anywhere else to be.",
  },
];

// Dev-only guard: the Galaxy Map's planet list and the slug-hunt odds table
// must stay in the same order (the party-location index addresses both).
if (import.meta.env?.DEV) {
  const here = PLANETS.map((p) => p.name);
  const there = slugHuntOdds.areas;
  const aligned = here.length === there.length && here.every((n, i) => n === there[i]);
  console.assert(
    aligned,
    "planetData.js PLANETS and slugHuntOdds.json areas are out of sync -- regenerate odds (scripts/gen_odds.py) or fix planetData.js order",
    { planetData: here, slugHuntOdds: there }
  );
}
