import slugHuntOdds from "./slugHuntOdds.json";

// The Three Clusters (see docs/the-three-clusters-player-facing.md): each is
// its own star system, orbiting a shared gravitational anchor in the long
// "Great Year" cycle described there. The Galaxy Map renders one cluster
// large/focused at a time and the other two small in the background --
// clicking a background cluster brings it to the front.
//
// Each world's orbitRx/orbitRy/sizeR/periodSec/phaseDeg are LOCAL to its own
// cluster (star at local origin 0,0) -- GalaxyMap.jsx positions/scales the
// whole cluster as a group, so these numbers are sized for when a cluster is
// in the focused/front slot.
//
// ORDER MATTERS. PLANETS (below) flattens these in cluster order -- Threxa,
// Verrin, Kaeth, then Unclaimed -- and that flat index is the value stored in
// campaign_settings.slug_hunt_area. It must line up with slugHuntOdds.json's
// `areas` array (generated by scripts/gen_odds.py from the slug CSV); the
// assert at the bottom of this file fails loudly in dev if the two ever
// drift. To add/reorder/rename worlds: edit AREAS and the positionally
// indexed AFF/EXCLUDE tables in scripts/gen_odds.py together, re-run it,
// then mirror the order here.
export const CLUSTERS = [
  {
    key: "threxa",
    name: "The Threxa Combine",
    subtitle: "the Thresh Expanse",
    starType: "red-giant",
    blurb:
      "Orbiting a dying red giant. The Combine built its wealth and reputation on two things: the Yoke — a discipline that lets a Threxan fully bind and control a bonded slug — and the hunting culture that grew out of it. Civilian slug ownership is banned throughout their territory; Yoked slugs run their industry, their labor, and their military. They are widely feared, openly transactional, and will do business with almost anyone who can pay.",
    // Ordered inner -> outer by how hot/livable each world's own description
    // implies it is: volcanic/geyser/geothermal worlds closest to the dying
    // giant, then the industrial and capital worlds, with the open grassland
    // reserve -- the one world that actually needs mild, plant-friendly
    // conditions -- farthest out.
    worlds: [
      {
        name: "Cindrath",
        color: "#d5623c",
        orbitRx: 70,
        orbitRy: 43,
        sizeR: 15,
        periodSec: 55,
        phaseDeg: 140,
        blurb:
          "A volcanic world of black glass ridges and slow rivers of lava, chosen for Threxa's fleet command precisely because nothing grows here to get in the way. Warden recruits drill on obstacle courses laid over cooling flow fields, the heat a constant test of endurance. Command spires rise from the ash-fall like teeth, lit orange from below.",
      },
      {
        name: "Pyrsis Barrens",
        color: "#c9a98f",
        orbitRx: 108,
        orbitRy: 67,
        sizeR: 15,
        periodSec: 85,
        phaseDeg: 80,
        blurb:
          "A flat, scalding expanse of geysers and mineral crust, used almost exclusively as a Threxa labor camp. Steam rolls low and constant, swallowing sound and sight past a few dozen metres, and the ground is never quite as solid as it looks. Nobody is sent here who has a choice in the matter.",
      },
      {
        name: "Ashfall Rift",
        color: "#c17b4a",
        orbitRx: 146,
        orbitRy: 91,
        sizeR: 13,
        periodSec: 115,
        phaseDeg: 260,
        blurb:
          "Steep, geothermal-scarred mountains vent steam and heat from fissures that never quite close. An occupied population works the mineral seams under Threxa oversight, terraces and rope-bridges strung between ridgelines heavy with drifting ash. The air tastes of sulfur and effort.",
      },
      {
        name: "Vorn's Forge",
        color: "#8f97a3",
        orbitRx: 184,
        orbitRy: 114,
        sizeR: 16,
        periodSec: 150,
        phaseDeg: 320,
        blurb:
          "A shipyard world humming with industrial scale — hulls under construction, cargo lifters, and processing floors where captured slugs are bonded and yoked before shipping out across the Expanse. The work never stops; neither does the noise.",
      },
      {
        name: "The Wellspring",
        color: "#d9b45c",
        orbitRx: 222,
        orbitRy: 138,
        sizeR: 17,
        periodSec: 190,
        phaseDeg: 200,
        blurb:
          "The Combine's capital, raised inside ruins far older than Threxa itself — vast stone halls whose builders nobody now remembers. At its heart sits the Grand Coliseum, where sanctioned hunts and duels are broadcast across the whole Expanse. Power here runs on spectacle as much as on the Yoke.",
      },
      {
        name: "Kessa-9",
        color: "#b7c25a",
        orbitRx: 260,
        orbitRy: 161,
        sizeR: 14,
        periodSec: 230,
        phaseDeg: 20,
        blurb:
          "Open grassland rolls to every horizon under Threxa's dim red sky, kept deliberately without roads, towers, or permanent settlement. The Combine polices it just enough to keep the hunting grounds pristine — sanctioned parties come and go, and the tall grass never quite loses the smell of old blood. Slugs run wild here in numbers found almost nowhere else in the Expanse, which is exactly the point.",
      },
    ],
  },
  {
    key: "verrin",
    name: "The Verrin Concord",
    subtitle: "the Lattice",
    starType: "binary",
    blurb:
      "Orbiting a close binary star pair. The Concord isn't a military power — it's a trade alliance, plural and pragmatic, that does business with everyone, Threxa included, and stays carefully neutral in anything it calls \"internal\" to another power's affairs. Wealth and access matter more here than ideology.",
    // Ordered inner -> outer by how much each world's description leans on
    // the binary pair's light and warmth: jungle and farmland need it most,
    // the finance world -- all towers and paperwork, "coldly fair" -- least.
    worlds: [
      {
        name: "Virid Canopy",
        color: "#6fae55",
        orbitRx: 80,
        orbitRy: 50,
        sizeR: 17,
        periodSec: 60,
        phaseDeg: 170,
        blurb:
          "A dense jungle world held as a Concord resource concession, its endless canopy worked for timber and rare compounds found nowhere else. Extraction crews clear paths that the forest reclaims within a season. Under all that green, something is always still growing back.",
      },
      {
        name: "Solenne",
        color: "#d0c26a",
        orbitRx: 122,
        orbitRy: 76,
        sizeR: 13,
        periodSec: 95,
        phaseDeg: 250,
        blurb:
          "Wide cultivated fields and orchard terraces stretch under the soft double daylight of the binary pair, supplying much of the Lattice's food. Life here is unhurried and practical, the kind of place that quietly keeps an entire trade alliance fed.",
      },
      {
        name: "Maren's Deep",
        color: "#3f8fc4",
        orbitRx: 165,
        orbitRy: 102,
        sizeR: 15,
        periodSec: 135,
        phaseDeg: 10,
        blurb:
          "An ocean world with no true land, its long-settled population living in floating city-states that rise and fall gently on the swell. Government, history, and old grudges all run deep here, independent of the Concord that nominally hosts them. Light off the twin suns scatters silver across open water in every direction.",
      },
      {
        name: "Aurelia Docks",
        color: "#cbb98a",
        orbitRx: 207,
        orbitRy: 128,
        sizeR: 16,
        periodSec: 175,
        phaseDeg: 130,
        blurb:
          "A sprawling shipyard-and-market world treated as neutral ground by every power in the Three Clusters. Threxan agents, Dominion officers, Concord traders, and plenty of people who'd rather not say who they work for all do business here in the open. If it can be bought, sold, or smuggled, it passes through the Docks eventually.",
      },
      {
        name: "Kethrun Reach",
        color: "#5b8a8f",
        orbitRx: 250,
        orbitRy: 155,
        sizeR: 12,
        periodSec: 220,
        phaseDeg: 40,
        blurb:
          "A world of towers, ledgers, and courts — the place to go for contracts, shipping law, and ownership disputes across the Lattice. Nothing moves here without paperwork, and paperwork here can move mountains. It is scrupulously, coldly fair, which is its own kind of ruthless.",
      },
    ],
  },
  {
    key: "kaeth",
    name: "The Kaeth Dominion",
    subtitle: "the Ironvault",
    starType: "black-hole",
    blurb:
      "Orbiting the accretion disc of a black hole. The Dominion is a militarist, expansionist power, openly rivalrous with Threxa over territory and resources rather than ideology. Their economy runs on conscription and total-war production rather than slugs or trade.",
    // Ordered inner -> outer by proximity to the accretion disc's heat: the
    // one explicitly warm world (the swamp) sits closest, the icebound
    // capital -- deliberately hardened by cold and distance -- farthest, with
    // the border station (watching the *edge* of Dominion space) out near it.
    worlds: [
      {
        name: "Marrek's Hold",
        color: "#4f6b4a",
        orbitRx: 80,
        orbitRy: 50,
        sizeR: 15,
        periodSec: 65,
        phaseDeg: 190,
        blurb:
          "A swamp world held under open Dominion occupation, its wetlands threaded with patrol causeways and checkpoint towers. The air is thick, warm, and always faintly toxic; the locals have learned exactly how far they're allowed to go, and no further.",
      },
      {
        name: "Drennow Yards",
        color: "#7f8a99",
        orbitRx: 122,
        orbitRy: 76,
        sizeR: 14,
        periodSec: 100,
        phaseDeg: 60,
        blurb:
          "An asteroid-belt complex strung with docking scaffolds and foundries, building the Dominion's warships one hull at a time. Rock and metal drift between work sites in slow, engineered orbits, and the accretion disc's glow never quite reaches the shadowed depths between them.",
      },
      {
        name: "Vhalden",
        color: "#a08a6a",
        orbitRx: 165,
        orbitRy: 102,
        sizeR: 14,
        periodSec: 140,
        phaseDeg: 150,
        blurb:
          "A harsh, wind-scoured training world where Dominion conscripts are broken down and rebuilt into soldiers. Obstacle ranges scar the terrain for kilometres in every direction, and the drop in temperature at night is considered part of the curriculum.",
      },
      {
        name: "Ossuary Station",
        color: "#4a4d55",
        orbitRx: 207,
        orbitRy: 128,
        sizeR: 12,
        periodSec: 180,
        phaseDeg: 20,
        blurb:
          "A fortified outpost bristling with sensor arrays and gun emplacements, watching the border with Threxa space around the clock. Named, the story goes, for what was found drifting nearby when the Dominion first claimed the position. Nothing about it has gotten less grim since.",
      },
      {
        name: "Kaeloth Prime",
        color: "#a9d6e5",
        orbitRx: 250,
        orbitRy: 155,
        sizeR: 16,
        periodSec: 225,
        phaseDeg: 300,
        blurb:
          "An icebound homeworld under the pale, restless light thrown off the accretion disc, its cities built low and armored against the cold. Every street here answers to the Dominion's military command, and every child grows up expecting conscription. It is beautiful in a hard, unforgiving way — glacier-blue, silent, absolutely disciplined.",
      },
    ],
  },
];

// Unclaimed Space isn't part of the three-cluster convergence cycle -- it
// drifts on its own in the open space between them (see GalaxyMap.jsx).
export const UNCLAIMED = {
  key: "unclaimed",
  name: "Unclaimed Space",
  subtitle: null,
  worlds: [
    {
      name: "The Threshold",
      color: "#8a6a52",
      sizeR: 11,
      blurb:
        "A vast graveyard of derelict hulls drifting in open space between the clusters, claimed by no power and policed by none. Scavengers, outcasts, and people from all Three Clusters who ran out of good options call it home, picking the wrecks for parts and stories in equal measure. Out here, the old rules simply don't apply.",
    },
  ],
};

// Flat, cluster-ordered list of every charted world -- this is what
// campaign_settings.slug_hunt_area indexes into, and what SlugHuntPanel and
// GalaxyMap's party marker use. See the ordering note at the top of this file.
export const PLANETS = [
  ...CLUSTERS.flatMap((cluster) =>
    cluster.worlds.map((world) => ({ ...world, clusterKey: cluster.key, clusterName: cluster.name }))
  ),
  ...UNCLAIMED.worlds.map((world) => ({ ...world, clusterKey: UNCLAIMED.key, clusterName: UNCLAIMED.name })),
];

// Dev-only guard: the Galaxy Map's flat planet list and the slug-hunt odds
// table must stay in the same order (the party-location index addresses both).
if (import.meta.env?.DEV) {
  const here = PLANETS.map((p) => p.name);
  const there = slugHuntOdds.areas;
  const aligned = here.length === there.length && here.every((n, i) => n === there[i]);
  console.assert(
    aligned,
    "planetData.js PLANETS and slugHuntOdds.json areas are out of sync -- regenerate odds (scripts/gen_odds.py) or fix planetData.js order",
    { planetData: here, slugHuntOdds: there }
  );
}
