// Seeds the DM's slug-template gallery with the default OG Slugterra roster
// (docs/Slugs - OG Slugs.csv) from server/src/data/defaultSlugTemplates.json,
// generated by scripts/generate-default-slug-templates.js. Runs once at every
// server startup (see index.js), and again on demand from the "Import
// Default Slugs" button on the Slug Templates page (see routes/slugTemplates.js's
// POST /import-defaults) -- either way it only ever INSERTs a name that
// isn't already in slug_templates, so re-running it never overwrites a
// default the DM has since edited, renamed, or deleted, and never touches
// custom/homebrew slugs added later either way. Pair with "Remove All
// Templates" on that same page for a clean re-import after regenerating the
// JSON from an updated CSV.
import { readFileSync, existsSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { pool } from "./db.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_PATH = path.join(__dirname, "data", "defaultSlugTemplates.json");

// Returns { available, seeded, total } -- `available` is false if
// generate-default-slug-templates.js has never been run (no JSON to seed
// from yet), so the caller (the startup log, or the import-defaults route)
// can tell "nothing to do" apart from "seeded 0 because they're all already
// there."
export async function seedDefaultSlugTemplates() {
  if (!existsSync(DATA_PATH)) return { available: false, seeded: 0, total: 0 };

  let defaults;
  try {
    defaults = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  } catch (err) {
    console.error("Could not read default slug templates:", err);
    return { available: false, seeded: 0, total: 0 };
  }
  if (!Array.isArray(defaults) || defaults.length === 0) return { available: false, seeded: 0, total: 0 };

  const { rows: existing } = await pool.query("SELECT name FROM slug_templates");
  const existingNames = new Set(existing.map((r) => r.name));

  let seeded = 0;
  for (const t of defaults) {
    if (existingNames.has(t.name)) continue;
    try {
      await pool.query(
        `INSERT INTO slug_templates
          (name, type, protoform_image, velocity_image, clash_power, clash_defense, ap_cost, max_energy_pips,
           loyalty_tier, velocity_ability, protoform_utility, breaks_walls, causes_knockback, wall_maker, bridge_maker, aoe_blast, hazard_maker,
           causes_blind, causes_snare, causes_shock, causes_jam,
           pierces_walls, causes_chain, ricochets, ultra_fast, causes_invisible, causes_fear, causes_confusion, trail_wall, clash_tripled,
           cone_blast, spawns_pods, mirage_decoy, star_wall, anchor_zone, voids_fire_clash, clears_fire_terrain,
           causes_disarm, disarm_zone, mind_scramble, swaps_position, friction_shift, crosswind_zone, skips_reload,
           emotion_surge, uncounterable, damage_tripled, static_mark, rarity)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49)`,
        [
          t.name,
          t.type,
          t.protoformImage ?? null,
          t.velocityImage ?? null,
          t.clashPower,
          t.clashDefense,
          t.apCost,
          t.maxEnergyPips,
          t.loyaltyTier ?? 0,
          t.velocityAbility ?? null,
          t.protoformUtility ?? null,
          Boolean(t.breaksWalls),
          Boolean(t.causesKnockback),
          Boolean(t.wallMaker),
          Boolean(t.bridgeMaker),
          Boolean(t.aoeBlast),
          Boolean(t.hazardMaker),
          Boolean(t.causesBlind),
          Boolean(t.causesSnare),
          Boolean(t.causesShock),
          Boolean(t.causesJam),
          Boolean(t.piercesWalls),
          Boolean(t.causesChain),
          Boolean(t.ricochets),
          Boolean(t.ultraFast),
          Boolean(t.causesInvisible),
          Boolean(t.causesFear),
          Boolean(t.causesConfusion),
          Boolean(t.trailWall),
          Boolean(t.clashTripled),
          Boolean(t.coneBlast),
          Boolean(t.spawnsPods),
          Boolean(t.mirageDecoy),
          Boolean(t.starWall),
          Boolean(t.anchorZone),
          Boolean(t.voidsFireClash),
          Boolean(t.clearsFireTerrain),
          Boolean(t.causesDisarm),
          Boolean(t.disarmZone),
          Boolean(t.mindScramble),
          Boolean(t.swapsPosition),
          Boolean(t.frictionShift),
          Boolean(t.crosswindZone),
          Boolean(t.skipsReload),
          Boolean(t.emotionSurge),
          Boolean(t.uncounterable),
          Boolean(t.damageTripled),
          Boolean(t.staticMark),
          t.rarity ?? null,
        ]
      );
      seeded++;
    } catch (err) {
      console.error(`Could not seed default slug "${t.name}":`, err);
    }
  }
  if (seeded > 0) console.log(`Seeded ${seeded} default slug template(s).`);
  return { available: true, seeded, total: defaults.length };
}

// `rarity` was added to slug_templates after the OG roster was already seeded
// on most databases, so those rows have a NULL rarity. Fill them in from the
// default JSON, matched by name -- but only where it's still NULL, so a rarity
// the DM has since set by hand is never clobbered. Runs once per startup after
// seedDefaultSlugTemplates(); a no-op once every default row has a value.
export async function backfillSlugTemplateRarity() {
  if (!existsSync(DATA_PATH)) return { updated: 0 };
  let defaults;
  try {
    defaults = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  } catch {
    return { updated: 0 };
  }
  if (!Array.isArray(defaults)) return { updated: 0 };

  let updated = 0;
  for (const t of defaults) {
    if (t.rarity === undefined || t.rarity === null) continue;
    const { rowCount } = await pool.query(
      "UPDATE slug_templates SET rarity = $1 WHERE name = $2 AND rarity IS NULL",
      [t.rarity, t.name]
    );
    updated += rowCount;
  }
  if (updated > 0) console.log(`Backfilled rarity on ${updated} slug template(s).`);
  return { updated };
}

// Speedstinger shipped with its whole ricochet mechanic wired up in combat
// code (see maybeRicochet in routes/combat.js) but the `ricochets` flag was
// never actually set TRUE on it -- in the source CSV, the generated JSON, or
// any seeded row -- so it never once bounced. The data is fixed now, but
// seedDefaultSlugTemplates() only ever INSERTs new names; it never updates a
// row that's already there. This turns the flag on for the existing
// Speedstinger template and every slug instance minted from it -- but only
// where it's still FALSE, so a DM who has since deliberately toggled it
// (either direction) is never overridden. One-off, same shape as
// backfillSlugTemplateRarity above; a no-op once every Speedstinger row has
// it set.
export async function backfillSpeedstingerRicochet() {
  const { rows: templates } = await pool.query(
    "UPDATE slug_templates SET ricochets = true WHERE name = 'Speedstinger' AND ricochets = false RETURNING id"
  );
  const templateIds = templates.map((r) => r.id);
  let instanceCount = 0;
  if (templateIds.length > 0) {
    const { rowCount } = await pool.query(
      "UPDATE slugs SET ricochets = true WHERE ricochets = false AND (template_id = ANY($1::int[]) OR name = 'Speedstinger')",
      [templateIds]
    );
    instanceCount = rowCount;
  } else {
    // Template already correct (or renamed/deleted) -- still catch loose
    // instances that predate the fix.
    const { rowCount } = await pool.query(
      "UPDATE slugs SET ricochets = true WHERE ricochets = false AND name = 'Speedstinger'"
    );
    instanceCount = rowCount;
  }
  if (templateIds.length > 0 || instanceCount > 0) {
    console.log(`Backfilled ricochets on ${templateIds.length} Speedstinger template(s) and ${instanceCount} slug(s).`);
  }
  return { templates: templateIds.length, instances: instanceCount };
}
