// Seeds the DM's slug-template gallery with the default OG Slugterra roster
// (docs/Slugs - OG Slugs.csv) from server/src/data/defaultSlugTemplates.json,
// generated by scripts/generate-default-slug-templates.js. Runs once at every
// server startup (see index.js), and again on demand from the "Import
// Default Slugs" button on the Slug Templates page (see routes/slugTemplates.js's
// POST /import-defaults) -- either way it only ever INSERTs a name that
// isn't already in slug_templates, so re-running it never overwrites a
// default the DM has since edited, renamed, or deleted, and never touches
// custom/homebrew slugs added later either way. Pair with "Remove All
// Templates" on that same page for a clean re-import after regenerating the
// JSON from an updated CSV.
import { readFileSync, existsSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { pool } from "./db.js";
import { syncTempoAura } from "./slugAura.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_PATH = path.join(__dirname, "data", "defaultSlugTemplates.json");

// Returns { available, seeded, total } -- `available` is false if
// generate-default-slug-templates.js has never been run (no JSON to seed
// from yet), so the caller (the startup log, or the import-defaults route)
// can tell "nothing to do" apart from "seeded 0 because they're all already
// there."
export async function seedDefaultSlugTemplates() {
  if (!existsSync(DATA_PATH)) return { available: false, seeded: 0, total: 0 };

  let defaults;
  try {
    defaults = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  } catch (err) {
    console.error("Could not read default slug templates:", err);
    return { available: false, seeded: 0, total: 0 };
  }
  if (!Array.isArray(defaults) || defaults.length === 0) return { available: false, seeded: 0, total: 0 };

  const { rows: existing } = await pool.query("SELECT name FROM slug_templates");
  const existingNames = new Set(existing.map((r) => r.name));

  let seeded = 0;
  for (const t of defaults) {
    if (existingNames.has(t.name)) continue;
    try {
      await pool.query(
        `INSERT INTO slug_templates
          (name, type, protoform_image, velocity_image, clash_power, clash_defense, ap_cost, max_energy_pips,
           loyalty_tier, velocity_ability, protoform_utility, breaks_walls, causes_knockback, wall_maker, bridge_maker, aoe_blast, hazard_maker,
           causes_blind, causes_snare, causes_shock, causes_jam,
           pierces_walls, causes_chain, ricochets, ultra_fast, causes_invisible, causes_fear, causes_confusion, trail_wall, clash_tripled,
           cone_blast, spawns_pods, mirage_decoy, star_wall, anchor_zone, voids_fire_clash, clears_fire_terrain,
           causes_disarm, disarm_zone, mind_scramble, swaps_position, friction_shift, crosswind_zone, skips_reload,
           emotion_surge, uncounterable, damage_tripled, static_mark, tempo_aura, power_surge, rarity)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35,$36,$37,$38,$39,$40,$41,$42,$43,$44,$45,$46,$47,$48,$49,$50,$51)`,
        [
          t.name,
          t.type,
          t.protoformImage ?? null,
          t.velocityImage ?? null,
          t.clashPower,
          t.clashDefense,
          t.apCost,
          t.maxEnergyPips,
          t.loyaltyTier ?? 0,
          t.velocityAbility ?? null,
          t.protoformUtility ?? null,
          Boolean(t.breaksWalls),
          Boolean(t.causesKnockback),
          Boolean(t.wallMaker),
          Boolean(t.bridgeMaker),
          Boolean(t.aoeBlast),
          Boolean(t.hazardMaker),
          Boolean(t.causesBlind),
          Boolean(t.causesSnare),
          Boolean(t.causesShock),
          Boolean(t.causesJam),
          Boolean(t.piercesWalls),
          Boolean(t.causesChain),
          Boolean(t.ricochets),
          Boolean(t.ultraFast),
          Boolean(t.causesInvisible),
          Boolean(t.causesFear),
          Boolean(t.causesConfusion),
          Boolean(t.trailWall),
          Boolean(t.clashTripled),
          Boolean(t.coneBlast),
          Boolean(t.spawnsPods),
          Boolean(t.mirageDecoy),
          Boolean(t.starWall),
          Boolean(t.anchorZone),
          Boolean(t.voidsFireClash),
          Boolean(t.clearsFireTerrain),
          Boolean(t.causesDisarm),
          Boolean(t.disarmZone),
          Boolean(t.mindScramble),
          Boolean(t.swapsPosition),
          Boolean(t.frictionShift),
          Boolean(t.crosswindZone),
          Boolean(t.skipsReload),
          Boolean(t.emotionSurge),
          Boolean(t.uncounterable),
          Boolean(t.damageTripled),
          Boolean(t.staticMark),
          Boolean(t.tempoAura),
          Boolean(t.powerSurge),
          t.rarity ?? null,
        ]
      );
      seeded++;
    } catch (err) {
      console.error(`Could not seed default slug "${t.name}":`, err);
    }
  }
  if (seeded > 0) console.log(`Seeded ${seeded} default slug template(s).`);
  return { available: true, seeded, total: defaults.length };
}

// `rarity` was added to slug_templates after the OG roster was already seeded
// on most databases, so those rows have a NULL rarity. Fill them in from the
// default JSON, matched by name -- but only where it's still NULL, so a rarity
// the DM has since set by hand is never clobbered. Runs once per startup after
// seedDefaultSlugTemplates(); a no-op once every default row has a value.
export async function backfillSlugTemplateRarity() {
  if (!existsSync(DATA_PATH)) return { updated: 0 };
  let defaults;
  try {
    defaults = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  } catch {
    return { updated: 0 };
  }
  if (!Array.isArray(defaults)) return { updated: 0 };

  let updated = 0;
  for (const t of defaults) {
    if (t.rarity === undefined || t.rarity === null) continue;
    const { rowCount } = await pool.query(
      "UPDATE slug_templates SET rarity = $1 WHERE name = $2 AND rarity IS NULL",
      [t.rarity, t.name]
    );
    updated += rowCount;
  }
  if (updated > 0) console.log(`Backfilled rarity on ${updated} slug template(s).`);
  return { updated };
}

// Speedstinger shipped with its whole ricochet mechanic wired up in combat
// code (see maybeRicochet in routes/combat.js) but the `ricochets` flag was
// never actually set TRUE on it -- in the source CSV, the generated JSON, or
// any seeded row -- so it never once bounced. The data is fixed now, but
// seedDefaultSlugTemplates() only ever INSERTs new names; it never updates a
// row that's already there. This turns the flag on for the existing
// Speedstinger template and every slug instance minted from it -- but only
// where it's still FALSE, so a DM who has since deliberately toggled it
// (either direction) is never overridden. One-off, same shape as
// backfillSlugTemplateRarity above; a no-op once every Speedstinger row has
// it set.
export async function backfillSpeedstingerRicochet() {
  const { rows: templates } = await pool.query(
    "UPDATE slug_templates SET ricochets = true WHERE name = 'Speedstinger' AND ricochets = false RETURNING id"
  );
  const templateIds = templates.map((r) => r.id);
  let instanceCount = 0;
  if (templateIds.length > 0) {
    const { rowCount } = await pool.query(
      "UPDATE slugs SET ricochets = true WHERE ricochets = false AND (template_id = ANY($1::int[]) OR name = 'Speedstinger')",
      [templateIds]
    );
    instanceCount = rowCount;
  } else {
    // Template already correct (or renamed/deleted) -- still catch loose
    // instances that predate the fix.
    const { rowCount } = await pool.query(
      "UPDATE slugs SET ricochets = true WHERE ricochets = false AND name = 'Speedstinger'"
    );
    instanceCount = rowCount;
  }
  if (templateIds.length > 0 || instanceCount > 0) {
    console.log(`Backfilled ricochets on ${templateIds.length} Speedstinger template(s) and ${instanceCount} slug(s).`);
  }
  return { templates: templateIds.length, instances: instanceCount };
}

// Fandango was reworked from a plain confusion slug into a Tempo Aura
// (passive) + Power Surge (velocity) slug -- see TEMPO_* / POWER_SURGE_* in
// combatRules.js and slugAura.js. The default JSON/CSV carry the new flags and
// text, but seedDefaultSlugTemplates() only ever INSERTs names it hasn't seen,
// so every already-seeded Fandango template (and every slug minted from one)
// still has the old text and neither flag. This upgrades those rows -- each
// half keyed off that half's *old default text* still being there, so a DM
// who has since edited the text or toggled the flags by hand is never
// overridden, and it's a no-op once every row has been upgraded. Any owner
// who just gained the aura gets their slugs' pips resized to match.
const OLD_FANDANGO_PROTOFORM =
  "Has an aura of energy that allows other slugs to recover quicker and last longer in duels before misfiring";
const OLD_FANDANGO_VELOCITY =
  "Morphs into a glowing chronomancer that rattles whoever it hits -- for the next 3 of their own turns, that target's own shots have a real chance of firing a complete 180 off target, not just a small miss.";

export async function backfillFandangoTempo() {
  if (!existsSync(DATA_PATH)) return { updated: 0 };
  let fandango;
  try {
    fandango = JSON.parse(readFileSync(DATA_PATH, "utf8")).find((t) => t.name === "Fandango");
  } catch {
    return { updated: 0 };
  }
  if (!fandango?.protoformUtility || !fandango?.velocityAbility) return { updated: 0 };

  let updated = 0;
  const owners = new Map();
  for (const table of ["slug_templates", "slugs"]) {
    const returning = table === "slugs" ? "RETURNING user_id, owner_combatant_id" : "RETURNING id";
    const aura = await pool.query(
      `UPDATE ${table} SET tempo_aura = true, protoform_utility = $1 WHERE name = 'Fandango' AND protoform_utility = $2 ${returning}`,
      [fandango.protoformUtility, OLD_FANDANGO_PROTOFORM]
    );
    const surge = await pool.query(
      `UPDATE ${table} SET power_surge = true, velocity_ability = $1 WHERE name = 'Fandango' AND velocity_ability = $2 ${returning}`,
      [fandango.velocityAbility, OLD_FANDANGO_VELOCITY]
    );
    updated += aura.rowCount + surge.rowCount;
    if (table === "slugs") {
      for (const row of [...aura.rows, ...surge.rows]) {
        owners.set(`${row.user_id}:${row.owner_combatant_id}`, { userId: row.user_id, ownerCombatantId: row.owner_combatant_id });
      }
    }
  }
  for (const owner of owners.values()) await syncTempoAura(owner);
  if (updated > 0) console.log(`Upgraded Fandango on ${updated} template/slug row(s).`);
  return { updated };
}
