// Seeds the DM's slug-template gallery with the default OG Slugterra roster
// (docs/Slugs - OG Slugs.csv) from server/src/data/defaultSlugTemplates.json,
// generated by scripts/generate-default-slug-templates.js. Runs once at every
// server startup (see index.js), and again on demand from the "Import
// Default Slugs" button on the Slug Templates page (see routes/slugTemplates.js's
// POST /import-defaults) -- either way it only ever INSERTs a name that
// isn't already in slug_templates, so re-running it never overwrites a
// default the DM has since edited, renamed, or deleted, and never touches
// custom/homebrew slugs added later either way. Pair with "Remove All
// Templates" on that same page for a clean re-import after regenerating the
// JSON from an updated CSV.
import { readFileSync, existsSync } from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { pool } from "./db.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_PATH = path.join(__dirname, "data", "defaultSlugTemplates.json");

// Returns { available, seeded, total } -- `available` is false if
// generate-default-slug-templates.js has never been run (no JSON to seed
// from yet), so the caller (the startup log, or the import-defaults route)
// can tell "nothing to do" apart from "seeded 0 because they're all already
// there."
export async function seedDefaultSlugTemplates() {
  if (!existsSync(DATA_PATH)) return { available: false, seeded: 0, total: 0 };

  let defaults;
  try {
    defaults = JSON.parse(readFileSync(DATA_PATH, "utf8"));
  } catch (err) {
    console.error("Could not read default slug templates:", err);
    return { available: false, seeded: 0, total: 0 };
  }
  if (!Array.isArray(defaults) || defaults.length === 0) return { available: false, seeded: 0, total: 0 };

  const { rows: existing } = await pool.query("SELECT name FROM slug_templates");
  const existingNames = new Set(existing.map((r) => r.name));

  let seeded = 0;
  for (const t of defaults) {
    if (existingNames.has(t.name)) continue;
    try {
      await pool.query(
        `INSERT INTO slug_templates
          (name, type, protoform_image, velocity_image, clash_power, clash_defense, ap_cost, max_energy_pips,
           loyalty_tier, velocity_ability, protoform_utility, breaks_walls, causes_knockback, wall_maker, bridge_maker, aoe_blast, hazard_maker,
           causes_blind, causes_snare, causes_shock, causes_jam,
           pierces_walls, causes_chain, ricochets, ultra_fast, causes_invisible, causes_fear, causes_confusion, trail_wall, clash_tripled,
           cone_blast, spawns_pods, mirage_decoy, star_wall, anchor_zone)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33,$34,$35)`,
        [
          t.name,
          t.type,
          t.protoformImage ?? null,
          t.velocityImage ?? null,
          t.clashPower,
          t.clashDefense,
          t.apCost,
          t.maxEnergyPips,
          t.loyaltyTier ?? 0,
          t.velocityAbility ?? null,
          t.protoformUtility ?? null,
          Boolean(t.breaksWalls),
          Boolean(t.causesKnockback),
          Boolean(t.wallMaker),
          Boolean(t.bridgeMaker),
          Boolean(t.aoeBlast),
          Boolean(t.hazardMaker),
          Boolean(t.causesBlind),
          Boolean(t.causesSnare),
          Boolean(t.causesShock),
          Boolean(t.causesJam),
          Boolean(t.piercesWalls),
          Boolean(t.causesChain),
          Boolean(t.ricochets),
          Boolean(t.ultraFast),
          Boolean(t.causesInvisible),
          Boolean(t.causesFear),
          Boolean(t.causesConfusion),
          Boolean(t.trailWall),
          Boolean(t.clashTripled),
          Boolean(t.coneBlast),
          Boolean(t.spawnsPods),
          Boolean(t.mirageDecoy),
          Boolean(t.starWall),
          Boolean(t.anchorZone),
        ]
      );
      seeded++;
    } catch (err) {
      console.error(`Could not seed default slug "${t.name}":`, err);
    }
  }
  if (seeded > 0) console.log(`Seeded ${seeded} default slug template(s).`);
  return { available: true, seeded, total: defaults.length };
}
